### ISSUE TITLE
Solicitud para utilizar código

### ISSUE THREAD

**Issue by andr3slelouch** [DannyGuevara-hub/facturas_electronicas_analisis_sri#1]
Hola, estoy iniciando un pequeño proyecto para extraer datos de facturas del SRI, quisiera empezar basándome en su código, pero al no tener un archivo LICENSE en el repositorio, me vi en la necesidad de solicitar permiso expresamente con ud, espero su pronta respuesta.
Saludos.

**Comment by DannyGuevara-hub** [comment]
Buen día.
Agradezco que se comunique conmigo.
Le autorizo a que use el script de facturas_electronicas_analisis_sri para
cualquier fin que tenga.
Espero que este pequeño script le sea de utilidad.

Cordialmente,
Danny Guevara <https://www.linkedin.com/in/danny-guevara/>

**Comment by andr3slelouch** [comment]
Muchas gracias por su respuesta, me aseguraré de referenciarlo y me es de mucha utilidad para mi proyecto.
Saludos.
